[[redirects]]
  from = "/index.html"
  to = "/login.html"
  status = 301
  force = false
  

[[redirects]]
  from = "/"
  to = "/login.html"
  status = 301
  force = false

[[redirects]]
  from = "/*"
  to = "/login.html"
  status = 301
  force = false
  
  