[[redirects]]
  from = "/"
  to = "/login.html"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}


[[redirects]]
  from = "/links.html"
  to = "/allProjects.html"
  status = 200
  force = true # COMMENT: ensure that we always redirect
  
